# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'from_designer/add_lot_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(678, 414)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("from_designer\\logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox = QtWidgets.QComboBox(Form)
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.setItemText(7, "")
        self.verticalLayout.addWidget(self.comboBox)
        self.tableWidget = QtWidgets.QTableWidget(Form)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(2)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(200)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.verticalLayout.addWidget(self.tableWidget)
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.line_edit_price = QtWidgets.QLineEdit(self.groupBox)
        self.line_edit_price.setObjectName("line_edit_price")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.line_edit_price)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.spinBox = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox.setObjectName("spinBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.spinBox)
        self.verticalLayout.addWidget(self.groupBox)
        self.groupBox_2 = QtWidgets.QGroupBox(Form)
        self.groupBox_2.setEnabled(True)
        self.groupBox_2.setObjectName("groupBox_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.groupBox_2)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.push_button_create = QtWidgets.QPushButton(self.groupBox_2)
        self.push_button_create.setObjectName("push_button_create")
        self.horizontalLayout.addWidget(self.push_button_create)
        self.push_button_close = QtWidgets.QPushButton(self.groupBox_2)
        self.push_button_close.setObjectName("push_button_close")
        self.horizontalLayout.addWidget(self.push_button_close)
        self.verticalLayout.addWidget(self.groupBox_2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Добавление лота"))
        self.comboBox.setItemText(0, _translate("Form", "Процессоры"))
        self.comboBox.setItemText(1, _translate("Form", "Мат. платы"))
        self.comboBox.setItemText(2, _translate("Form", "Видеокарты"))
        self.comboBox.setItemText(3, _translate("Form", "Охлаждение"))
        self.comboBox.setItemText(4, _translate("Form", "Оперативная память"))
        self.comboBox.setItemText(5, _translate("Form", "Накопители"))
        self.comboBox.setItemText(6, _translate("Form", "Блоки питания"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("Form", "Название"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("Form", "Краткая технич. хар-ка"))
        self.label.setText(_translate("Form", "Цена/шт"))
        self.label_2.setText(_translate("Form", "Кол-во"))
        self.push_button_create.setText(_translate("Form", "Создать лот"))
        self.push_button_close.setText(_translate("Form", "Отмена"))
