# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'from_designer/buy_lot_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(538, 272)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("from_designer\\logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_seller = QtWidgets.QLabel(self.groupBox)
        self.label_seller.setText("")
        self.label_seller.setObjectName("label_seller")
        self.gridLayout.addWidget(self.label_seller, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label_component = QtWidgets.QLabel(self.groupBox)
        self.label_component.setText("")
        self.label_component.setObjectName("label_component")
        self.gridLayout.addWidget(self.label_component, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_charac = QtWidgets.QLabel(self.groupBox)
        self.label_charac.setText("")
        self.label_charac.setObjectName("label_charac")
        self.gridLayout.addWidget(self.label_charac, 2, 1, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 3, 0, 1, 1)
        self.spinBox_count = QtWidgets.QSpinBox(self.groupBox)
        self.spinBox_count.setObjectName("spinBox_count")
        self.gridLayout.addWidget(self.spinBox_count, 3, 1, 1, 1)
        self.label_total_price = QtWidgets.QLabel(self.groupBox)
        self.label_total_price.setText("")
        self.label_total_price.setObjectName("label_total_price")
        self.gridLayout.addWidget(self.label_total_price, 4, 1, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 4, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.push_button_buy = QtWidgets.QPushButton(Form)
        self.push_button_buy.setObjectName("push_button_buy")
        self.horizontalLayout.addWidget(self.push_button_buy)
        self.push_button_close = QtWidgets.QPushButton(Form)
        self.push_button_close.setObjectName("push_button_close")
        self.horizontalLayout.addWidget(self.push_button_close)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Покупка"))
        self.label.setText(_translate("Form", "Продавец"))
        self.label_2.setText(_translate("Form", "Название комплектующего"))
        self.label_3.setText(_translate("Form", "Технические характеристики"))
        self.label_4.setText(_translate("Form", "Кол-во"))
        self.label_5.setText(_translate("Form", "Итоговая цена"))
        self.push_button_buy.setText(_translate("Form", "Купить"))
        self.push_button_close.setText(_translate("Form", "Отмена"))
