# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'from_designer/compability.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(469, 346)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.componentBox = QtWidgets.QComboBox(Form)
        self.componentBox.setObjectName("componentBox")
        self.componentBox.addItem("")
        self.componentBox.addItem("")
        self.componentBox.addItem("")
        self.componentBox.addItem("")
        self.componentBox.addItem("")
        self.gridLayout.addWidget(self.componentBox, 0, 0, 1, 1)
        self.text_label = QtWidgets.QLabel(Form)
        self.text_label.setObjectName("text_label")
        self.gridLayout.addWidget(self.text_label, 0, 1, 1, 1)
        self.componentTable = QtWidgets.QTableWidget(Form)
        self.componentTable.setObjectName("componentTable")
        self.componentTable.setColumnCount(0)
        self.componentTable.setRowCount(0)
        self.gridLayout.addWidget(self.componentTable, 1, 0, 1, 1)
        self.mbTable = QtWidgets.QTableWidget(Form)
        self.mbTable.setObjectName("mbTable")
        self.mbTable.setColumnCount(0)
        self.mbTable.setRowCount(0)
        self.gridLayout.addWidget(self.mbTable, 1, 1, 1, 1)
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 2, 0, 1, 2)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.componentBox.setItemText(0, _translate("Form", "Выберите тип комплектующего"))
        self.componentBox.setItemText(1, _translate("Form", "Центральный процессор"))
        self.componentBox.setItemText(2, _translate("Form", "Видеокарта"))
        self.componentBox.setItemText(3, _translate("Form", "Оперативная память"))
        self.componentBox.setItemText(4, _translate("Form", "Кулер"))
        self.text_label.setText(_translate("Form", "Материнская плата"))
        self.pushButton.setText(_translate("Form", "Проверка совместимости"))
