# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'from_designer/main_window.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(790, 580)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("from_designer\\logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        MainWindow.setWindowIcon(icon)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.push_button_sort = QtWidgets.QPushButton(self.centralwidget)
        self.push_button_sort.setObjectName("push_button_sort")
        self.verticalLayout.addWidget(self.push_button_sort)
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setSelectionBehavior(QtWidgets.QAbstractItemView.SelectRows)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(5)
        self.tableWidget.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        self.tableWidget.horizontalHeader().setCascadingSectionResizes(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(150)
        self.tableWidget.horizontalHeader().setHighlightSections(True)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(37)
        self.tableWidget.verticalHeader().setHighlightSections(True)
        self.verticalLayout.addWidget(self.tableWidget)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.push_button_create = QtWidgets.QPushButton(self.centralwidget)
        self.push_button_create.setObjectName("push_button_create")
        self.horizontalLayout.addWidget(self.push_button_create)
        self.push_button_buy = QtWidgets.QPushButton(self.centralwidget)
        self.push_button_buy.setObjectName("push_button_buy")
        self.horizontalLayout.addWidget(self.push_button_buy)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.push_button_receipts = QtWidgets.QPushButton(self.centralwidget)
        self.push_button_receipts.setObjectName("push_button_receipts")
        self.verticalLayout.addWidget(self.push_button_receipts)
        self.push_button_register = QtWidgets.QPushButton(self.centralwidget)
        self.push_button_register.setObjectName("push_button_register")
        self.verticalLayout.addWidget(self.push_button_register)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 790, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setSizeGripEnabled(True)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Магазин"))
        self.push_button_sort.setText(_translate("MainWindow", "Сортировка"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "id"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "Продавец"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("MainWindow", "Комплектующее"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("MainWindow", "Цена/шт"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("MainWindow", "Кол-во"))
        self.push_button_create.setText(_translate("MainWindow", "Добавить лот"))
        self.push_button_buy.setText(_translate("MainWindow", "Купить лот"))
        self.push_button_receipts.setText(_translate("MainWindow", "История Ваших сделок"))
        self.push_button_register.setText(_translate("MainWindow", "Войти под другим аккаунтом"))
