# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'from_designer/registration_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(435, 214)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("from_designer\\logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.groupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.groupBox)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 3, 0, 1, 2)
        self.line_edit_login = QtWidgets.QLineEdit(self.groupBox)
        self.line_edit_login.setObjectName("line_edit_login")
        self.gridLayout.addWidget(self.line_edit_login, 0, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.line_edit_password = QtWidgets.QLineEdit(self.groupBox)
        self.line_edit_password.setObjectName("line_edit_password")
        self.gridLayout.addWidget(self.line_edit_password, 1, 1, 1, 1)
        self.line_edit_FIO = QtWidgets.QLineEdit(self.groupBox)
        self.line_edit_FIO.setObjectName("line_edit_FIO")
        self.gridLayout.addWidget(self.line_edit_FIO, 2, 1, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 4, 0, 1, 1)
        self.verticalLayout.addWidget(self.groupBox)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Вход/Регистрация"))
        self.groupBox.setTitle(_translate("Form", "Вход/Регистрация"))
        self.label_2.setText(_translate("Form", "Пароль"))
        self.label.setText(_translate("Form", "Логин"))
        self.pushButton.setText(_translate("Form", "Войти/Зарегистрироваться"))
        self.label_3.setText(_translate("Form", "ФИО (при регистрации)"))
