# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'from_designer/update_lot_form.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(544, 332)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("from_designer\\logo.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        Form.setWindowIcon(icon)
        self.verticalLayout = QtWidgets.QVBoxLayout(Form)
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox = QtWidgets.QGroupBox(Form)
        self.groupBox.setObjectName("groupBox")
        self.formLayout = QtWidgets.QFormLayout(self.groupBox)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.label_seller = QtWidgets.QLabel(self.groupBox)
        self.label_seller.setText("")
        self.label_seller.setObjectName("label_seller")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_seller)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.label_4 = QtWidgets.QLabel(self.groupBox)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.line_edit_price = QtWidgets.QLineEdit(self.groupBox)
        self.line_edit_price.setObjectName("line_edit_price")
        self.formLayout.setWidget(6, QtWidgets.QFormLayout.FieldRole, self.line_edit_price)
        self.label_5 = QtWidgets.QLabel(self.groupBox)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.line_edit_count = QtWidgets.QLineEdit(self.groupBox)
        self.line_edit_count.setObjectName("line_edit_count")
        self.formLayout.setWidget(8, QtWidgets.QFormLayout.FieldRole, self.line_edit_count)
        self.label_3 = QtWidgets.QLabel(self.groupBox)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.label_component = QtWidgets.QLabel(self.groupBox)
        self.label_component.setText("")
        self.label_component.setObjectName("label_component")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.label_component)
        self.label_charac = QtWidgets.QLabel(self.groupBox)
        self.label_charac.setText("")
        self.label_charac.setObjectName("label_charac")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.label_charac)
        self.verticalLayout.addWidget(self.groupBox)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.push_button_update = QtWidgets.QPushButton(Form)
        self.push_button_update.setObjectName("push_button_update")
        self.horizontalLayout.addWidget(self.push_button_update)
        self.push_button_delete = QtWidgets.QPushButton(Form)
        self.push_button_delete.setObjectName("push_button_delete")
        self.horizontalLayout.addWidget(self.push_button_delete)
        self.push_button_close = QtWidgets.QPushButton(Form)
        self.push_button_close.setObjectName("push_button_close")
        self.horizontalLayout.addWidget(self.push_button_close)
        self.verticalLayout.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Просмотр лота"))
        self.label.setText(_translate("Form", "Продавец"))
        self.label_2.setText(_translate("Form", "Название комплектующего"))
        self.label_4.setText(_translate("Form", "Цена/шт"))
        self.label_5.setText(_translate("Form", "Кол-во"))
        self.label_3.setText(_translate("Form", "Технические характеристики"))
        self.push_button_update.setText(_translate("Form", "Обновить лот"))
        self.push_button_delete.setText(_translate("Form", "Удалить лот"))
        self.push_button_close.setText(_translate("Form", "Отмена"))
